# Generated by Django 6.0.3 on 2026-03-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0002_menucategory_remove_menu_cuisine_menu_category_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_name",
                to="demoapp.menucategory",
            ),
        ),
    ]
