# Generated by Django 6.0.3 on 2026-03-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0003_alter_menu_category_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=251)),
                (
                    "drinksChoice",
                    models.CharField(
                        choices=[
                            ("coffee", "coffee"),
                            ("tea", "tea"),
                            ("chantea", "chantea"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
