# Generated by Django 6.0.3 on 2026-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0004_applicationform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
            ],
        ),
    ]
